import os
from dotenv import load_dotenv
load_dotenv()
FINNHUB_KEY = os.getenv("finnhub_API")
import streamlit as st
import plotly.graph_objects as go

import data
import model
import forecast_model

from plotly.subplots import make_subplots  
import pandas as pd

# --- CONFIG ---
st.set_page_config(page_title="AI Stock Monitor", layout="wide")

# --- CACHING ---
@st.cache_resource
def get_ai_model():
    return model.load_finbert()

@st.cache_resource
def get_api_client():
    return data.init_finnhub(FINNHUB_KEY)

try:
    finbert = get_ai_model()
    client = get_api_client()
except Exception as e:
    st.error(f"Error loading resources: {e}")
    st.stop()

# --- SIDEBAR ---
st.sidebar.header("⚙️ Dashboard Settings")
available_tickers = data.get_ticker_list()
ticker = st.sidebar.selectbox(
    "Select Asset", 
    options=available_tickers, 
    index=available_tickers.index("GOOG") if "GOOG" in available_tickers else 0
)
days = st.sidebar.slider("Analysis Window (Days)", 30, 365, 90)


# --- DATA LOADING ---
st.title(f"🚀 {ticker} AI-Powered Analyst")

with st.spinner('Crunching numbers...'):
    prices = data.get_historical_prices(ticker, days)
    raw_news = data.get_latest_news(client, ticker)
    
    # Process Sentiment
    if raw_news:
        analyzed_news = model.analyze_news_list(raw_news, finbert)
    else:
        analyzed_news = []
    
    # Process Forecast
    forecast = forecast_model.generate_forecast(prices, days=7)

# --- TOP ROW: KPI METRICS ---
if prices is not None and not prices.empty:
    current_price = prices['Close'].iloc[-1]
    predicted_price = forecast['yhat'].iloc[-1]
    price_change = ((predicted_price - current_price) / current_price) * 100
    
    # Calculate Avg Sentiment Score
    avg_score = 0
    if analyzed_news:
        scores = [n['score'] if n['label']=='positive' else -n['score'] if n['label']=='negative' else 0 for n in analyzed_news]
        avg_score = sum(scores) / len(scores)
    
    m1, m2, m3 = st.columns(3)
    m1.metric("Current Price", f"${current_price:.2f}")
    m2.metric("AI 7-Day Target", f"${predicted_price:.2f}", f"{price_change:.2f}%")
    m3.metric("Market Sentiment", "Bullish" if avg_score > 0.1 else "Bearish" if avg_score < -0.1 else "Neutral", f"{avg_score:.2f}")

    st.divider()
    # --- TABS ---
    tab1, tab2 = st.tabs(["📈 Price & Forecast", "🧠 Sentiment Analysis"])

    with tab1:
        st.subheader("Price Action + AI Prediction")
        
        fig_main = go.Figure()

        # 1. Actual Price Candles
        fig_main.add_trace(go.Candlestick(
            x=prices.index,
            open=prices['Open'], high=prices['High'],
            low=prices['Low'], close=prices['Close'],
            name="Actual History"
        ))

        # 2. AI Forecast Line
        last_real_date = prices.index[-1].tz_localize(None)
        future_data = forecast[forecast['ds'] > last_real_date]

        fig_main.add_trace(go.Scatter(
            x=future_data['ds'], y=future_data['yhat'],
            mode='lines+markers', name="AI Prediction",
            line=dict(color='#00ffcc', width=3, dash='dash')
        ))

        # 3. Confidence Tunnel
        fig_main.add_trace(go.Scatter(
            x=future_data['ds'], y=future_data['yhat_upper'],
            mode='lines', line=dict(width=0), showlegend=False, hoverinfo='skip'
        ))
        fig_main.add_trace(go.Scatter(
            x=future_data['ds'], y=future_data['yhat_lower'],
            fill='tonexty', mode='lines', line=dict(width=0),
            fillcolor='rgba(0, 255, 204, 0.1)', name="Confidence Range"
        ))

        fig_main.update_layout(
            template="plotly_dark", height=600, 
            xaxis_rangeslider_visible=False,
            legend=dict(orientation="h", y=1.02, xanchor="right", x=1)
        )
        st.plotly_chart(fig_main, use_container_width=True)
        st.warning("⚠️ **Disclaimer:** This forecast is generated by an AI model based solely on historical price patterns. It does not account for real-world news, earnings reports, or macroeconomic events. **Do not trade based on this data.**")


    with tab2:
        col_sent_graph, col_news = st.columns([2, 1])
        
        with col_sent_graph:
            st.subheader("Sentiment Trend (Last 7 Days)")
            if analyzed_news:
                df_news = pd.DataFrame(analyzed_news)
                df_news['date'] = pd.to_datetime(df_news['datetime'], unit='s')
                df_news['val'] = df_news.apply(lambda x: x['score'] if x['label'] == 'positive' else -x['score'] if x['label'] == 'negative' else 0, axis=1)
                
                daily_sentiment = df_news.groupby(df_news['date'].dt.date)['val'].mean()

                fig_sent = go.Figure()
                fig_sent.add_trace(go.Scatter(
                    x=daily_sentiment.index, y=daily_sentiment.values,
                    mode='lines+markers', name="Sentiment Score",
                    line=dict(color='#ff9900', width=3), marker=dict(size=8)
                ))
                fig_sent.add_hline(y=0, line_dash="dot", line_color="gray")
                fig_sent.update_layout(template="plotly_dark", height=500)
                st.plotly_chart(fig_sent, use_container_width=True)
            else:
                st.info("Not enough news data to build a trend line.")

        with col_news:
            st.subheader("Latest Headlines")
            with st.container(height=500):
                if analyzed_news:
                    for item in analyzed_news:
                        color = "green" if item['label'] == 'positive' else "red" if item['label'] == 'negative' else "gray"
                        st.markdown(f"**{item['headline'][:60]}...**")
                        st.caption(f":{color}[{item['label'].upper()}] • Conf: {item['score']:.2f}")
                        st.markdown(f"[Read Source]({item['url']})")
                        st.divider()
else:
    st.warning("No data found for this ticker.")